### ISSUE TITLE
iOS 12-13

### ISSUE THREAD

**Issue by TheProgramableTurtle** [GeoSn0w/Blizzard-Jailbreak#10]
You removed the 'soon to support iOS 12 and 13' note in the README [here](https://github.com/GeoSn0w/Blizzard-Jailbreak/commit/1a04ce82852831d578e9f64e17d620b81259f81a). Do you still intend to support these versions?

**Comment by GeoSn0w** [comment]
This project is currently on hold because I am working mainly on iSecureOS, another jailbreak-related project, but this one has the advantage of actually being useful for everyone.

**Comment by TheProgramableTurtle** [comment]
I see, I hope you find time to pick it up again someday.
