### ISSUE TITLE
.DS_store

### ISSUE THREAD

**Issue by ghost** [GeoSn0w/Blizzard-Jailbreak#3]
silly mack users

**Comment by CydiaGod666** [comment]
وَقُلْ رَّبِّ اَعُوْذُ بِكَ مِنْ هَمَزٰتِ الشَّيٰطِيْنِ. وَاَعُوْذُ بِكَ رَبِّ اَنْ يَّحْضُرُوْنِ.

**Comment by rodent5** [comment]
what

**Comment by CydiaGod666** [comment]
أَعُوذُ بِاللَّهِ مِنَ الشَّيْطانِ الرَّجِيْمِ

**Comment by GeoSn0w** [comment]
This is now fixed.
