### ISSUE TITLE
no such file or directory: '/Users/exerhythm/Downloads/ToolChain/Jailbreak Frameworks/IOKit.tbd'

### ISSUE THREAD

**Issue by sourcelocation** [GeoSn0w/Blizzard-Jailbreak#8]
When I try to compile with Xcode, this error comes up. `no such file or directory: '/Users/exerhythm/Downloads/ToolChain/Jailbreak Frameworks/IOKit.tbd'
` Any fixes?

**Comment by GeoSn0w** [comment]
You'll need to add that file to the project yourself.
